import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import React from 'react'

// <Setup Blueprint>
import '@blueprintjs/core/lib/css/blueprint.css'
import '@blueprintjs/icons/lib/css/blueprint-icons.css'
import { Button, FocusStyleManager } from '@blueprintjs/core'
FocusStyleManager.onlyShowFocusOnTabs()

function DeemLogo(props: { style?: any }) {
  return (
    <h1
      style={{
        fontSize: '2.75rem',
        fontFamily: 'garamond, serif',
        ...props.style,
      }}
    >
      deem
    </h1>
  )
}

export default function Home() {
  const nav_ref = React.useRef<HTMLElement>()
  const scroll_timer = React.useRef<number>()
  React.useEffect(() => {
    document.addEventListener(
      'scroll',
      () => {
        clearTimeout(scroll_timer.current)

        scroll_timer.current = setTimeout(() => {
          if (!nav_ref.current) return
          if (window.scrollY != 0) {
            nav_ref.current.style.background = '#FFFFFF'
          }
          if (window.scrollY == 0) {
            nav_ref.current.style.background = '#FFFAF0'
          }
        }, 100)
      },
      { passive: true }
    )
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={styles.main}
        style={{
          borderBottom: '1px black dotted',
          gap: '7rem',
        }}
      >
        <nav
          ref={nav_ref}
          style={{
            width: '100%',
            borderBottom: '1px black dotted',
            position: 'sticky',
            top: '0px',
            background: '#FFFAF0',
            transition: 'background 0.25s ease-in',
          }}
        >
          <div
            style={{
              display: 'flex',
              padding: '1rem',
              maxWidth: '70rem',
              margin: '0 auto',
            }}
          >
            <DeemLogo style={{ color: '#FC8C79' }} />
            <div style={{ flexGrow: 1 }} />
            <Button
              large
              minimal
              outlined
              text="Join"
              style={{
                fontWeight: 'bold',
                margin: '0.5rem',
              }}
            ></Button>
          </div>
        </nav>

        <section
          id="tagline"
          style={{
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
          }}
        >
          <h2>
            <div
              style={{
                color: '#BF5748',
              }}
            >
              AI-powered accounting workflows
            </div>{' '}
            that save time and mitigate risk.
          </h2>
          <br />
          <article>
            <p>Use our advanced search to find relevant guidance in seconds.</p>
            <p>
              Use generative AI and your approved guidance to draft technical memos, giving your team a headstart of a
              variety of internal tasks.
            </p>
          </article>
          <br />

          <Button
            large
            minimal
            outlined
            text="Join the waitlist"
            style={{
              fontWeight: 'bold',
              margin: '0 auto',
              width: 'fit-content',
            }}
          ></Button>
        </section>
        <section
          id="tagline-image"
          style={{
            height: '25rem',
          }}
        >
          <Image
            alt="deem product image"
            height={500}
            width={500}
            src={'/next.svg'}
            style={{
              // border: "1px red solid ",
              width: '100%',
              maxWidth: '20rem',
            }}
          />
        </section>
        <section
          id="tagline-call-to-action"
          style={{
            // border: "1px solid red",
            // height: "10rem",
            width: '100%',
            display: 'flex',
            flexDirection: 'column',
          }}
        >
          <h2>Would you like to be an early adopter?</h2>
          <br />
          <article>
            <p>When you submit this form, your firm will join our early adopters waitlist.</p>
            <p>We will reach out shortly after to schedule an intro call.</p>
          </article>
          <br />
          <Button
            minimal
            outlined
            large
            text="Join the early adopters waitlist"
            style={{
              width: 'fit-content',
              fontWeight: 'bold',
              margin: '0 auto',
              color: '#BF5748',
            }}
          />
        </section>
        {/* empty div to allow flex gap to space out the bottom */}
        <div />
        <div />
      </main>
      <footer
        className={styles.footer}
        style={{
          maxWidth: '70rem',
          margin: '0 auto',
        }}
      >
        <div
          style={{
            display: 'flex',
          }}
        >
          <h2
            style={{
              display: 'grid',
              alignItems: 'center',
              paddingRight: '0.5rem',
            }}
          >
            Stay in touch
          </h2>
          <a
            href="https://www.linkedin.com/in/shane-au-wade"
            target="_blank"
            style={{
              display: 'grid',
              alignItems: 'center',
            }}
          >
            <Image
              src="/linkedin.svg"
              alt="linkedin social media icon"
              width={50}
              height={50}
              style={{
                width: '1.75rem',
                height: 'auto',
              }}
            />
          </a>
        </div>
        <div
          style={{
            flexGrow: 1,
          }}
        />

        <div style={{}}>
          <DeemLogo
            style={{
              fontSize: '2rem',
            }}
          />
          <sub
            style={{
              display: 'grid',
              alignItems: 'center',
              textAlign: 'right',
              margin: 0,
            }}
          >
            {`© 2023`}
          </sub>
        </div>
      </footer>
    </>
  )
}
